ci: testing rust lib

diff --git a/.github/workflows/test-bdk-ffi-latest.yaml b/.github/workflows/test-bdk-ffi-latest.yaml
--- a/.github/workflows/test-bdk-ffi-latest.yaml
+++ b/.github/workflows/test-bdk-ffi-latest.yaml
@@ -60,50 +60,50 @@ jobs:
           components: ${{inputs.components}}
           override: ${{inputs.override}}
           rust_src_dir: ${{inputs.rust-src-dir}}
-          shell: bash
-          run: |
-            echo "Current Directory: $(pwd)"
-            echo "Rust Source Directory: $rust_src_dir"
-            echo "Toolchain: $toolchain"
-            echo "Targets: $targets"
-            echo "Components: $components"
-            echo "Override: $override"
+        shell: bash
+        run: |
+          echo "Current Directory: $(pwd)"
+          echo "Rust Source Directory: $rust_src_dir"
+          echo "Toolchain: $toolchain"
+          echo "Targets: $targets"
+          echo "Components: $components"
+          echo "Override: $override"
 
-            if [[ -d "$rust_src_dir" ]]; then
-              cd "$rust_src_dir"
-              echo "Changed directory to: $(pwd)"
-            fi
+          if [[ -d "$rust_src_dir" ]]; then
+            cd "$rust_src_dir"
+            echo "Changed directory to: $(pwd)"
+          fi
 
-            if [[ -z "$toolchain" && ( -f "rust-toolchain" || -f "rust-toolchain.toml") ]]; then
-              echo "Installing toolchain from rust-toolchain file..."
-              rustup show active-toolchain || rustup toolchain install
-              if [[ $? -ne 0 ]]; then
-                echo "Error: Failed to install toolchain from rust-toolchain file."
-                exit 1
-              fi
-              if [[ -n $components ]]; then
-                echo "Adding components: ${components//,/ }"
-                rustup component add ${components//,/ }
-              fi
-              if [[ -n $targets ]]; then
-                echo "Adding targets: ${targets//,/ }"
-                rustup target add ${targets//,/ }
-              fi
-            else
-              if [[ -z "$toolchain" ]]; then
-                toolchain=stable
-              fi
-              echo "Installing specified toolchain: ${toolchain//,/ }"
-              rustup toolchain install ${toolchain//,/ } ${{steps.flags.outputs.targets}}${{steps.flags.outputs.components}} --profile minimal${{steps.flags.outputs.downgrade}} --no-self-update
-              if [[ $? -ne 0 ]]; then
-                echo "Error: Failed to install specified toolchain."
-                exit 1
-              fi
-              if [[ "$override" == "true" ]]; then
-                echo "Setting override to toolchain: ${toolchain//*,/ }"
-                rustup override set ${toolchain//*,/ }
-              fi
+          if [[ -z "$toolchain" && ( -f "rust-toolchain" || -f "rust-toolchain.toml") ]]; then
+            echo "Installing toolchain from rust-toolchain file..."
+            rustup show active-toolchain || rustup toolchain install
+            if [[ $? -ne 0 ]]; then
+              echo "Error: Failed to install toolchain from rust-toolchain file."
+              exit 1
             fi
+            if [[ -n $components ]]; then
+              echo "Adding components: ${components//,/ }"
+              rustup component add ${components//,/ }
+            fi
+            if [[ -n $targets ]]; then
+              echo "Adding targets: ${targets//,/ }"
+              rustup target add ${targets//,/ }
+            fi
+          else
+            if [[ -z "$toolchain" ]]; then
+              toolchain=stable
+            fi
+            echo "Installing specified toolchain: ${toolchain//,/ }"
+            rustup toolchain install ${toolchain//,/ } ${{steps.flags.outputs.targets}}${{steps.flags.outputs.components}} --profile minimal${{steps.flags.outputs.downgrade}} --no-self-update
+            if [[ $? -ne 0 ]]; then
+              echo "Error: Failed to install specified toolchain."
+              exit 1
+            fi
+            if [[ "$override" == "true" ]]; then
+              echo "Setting override to toolchain: ${toolchain//*,/ }"
+              rustup override set ${toolchain//*,/ }
+            fi
+          fi
                   
       - name: "Generate bdk.py and binaries"
         run: bash ./scripts/generate-linux.sh
